language: php

sudo: false

git:
    depth: 1

matrix:
    include:
        - php: hhvm
        - php: 5.6
        - php: 7.0
    fast_finish: true

cache:
    directories:
        - .phpunit
        - php-$MIN_PHP
        - $HOME/.composer/cache

services: mysql

before_script:
    - composer install

script: phpunit --configuration phpunit.xml.dist --coverage-text
