# Debugging services

services:
    
    stopwatch:
        class:      Symfony\Component\Stopwatch\Stopwatch
    
    dispatcher.debug:
        class:      Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher
        decorates:  dispatcher.default
        arguments:  [ "@dispatcher.debug.inner", "@stopwatch" ]
    
    dispatcher:
        alias:      dispatcher.debug
