# Define your own custom services here

imports:
    - { resource: "routes.yml" }

services:

    controller.base_web:
        lazy:               true
        abstract:           true
        class:              App\Controller\Base\WebController
        arguments:
            request:        "@request"
            templating:     "@templating.twig"
            entityManager:  "@doctrine.entity_manager"
            urlGenerator:   "@router.generator"

    controller.default:
        class:              App\Controller\DefaultController
        parent:             controller.base_web

    controller.page:
        class:              App\Controller\PageController
        arguments:          [ "@templating.twig", "@repository.page" ]
